# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  blog:
    output: true
    permalink: /blogs/:slug
  people:
    output: true
  research:
    output: true
    permalink: /:slug
  projects:
    output: true
    permalink: /:slug
  publications:
    output: true
    permalink: /publications/:title
  events:
    output: true
logo: logo.png
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
- jekyll-paginate
sass:
  sass_dir: _sass
# Pagination
paginate: 5
paginate_path: "blogs/page:num"
# for paginate-v2 (not supported by github pages)
# pagination:
  # enabled: true
  # per_page: 5
  # permalink: '/page/:num/'
  # title: ':title'
  # limit: 0
  # sort_field: 'date'
  # sort_reverse: true
remote_theme: datatrustsinitiative/jekyll-theme
style: mlatcl
description: This is the web presence of the data trusts initiative.
twitter_svg: ./assets/images/social-tw.svg
facebook_svg: ./assets/images/social-fb.svg
instagram_svg: ./assets/images/social-in.svg
image_root: ./assets/images/
baseurl: ''
markdown: kramdown
twitter_username: data
github_username: mlatcl
display:
  copy_button:
    bibtex: true
    endnote: true
    ris: true
    apa: true
  comments: false
ghub:
  edit: true
  repository: mlatcl.github.io
future: true
publisher: The Computer Laboratory
author:
  name: ML@CL
  github: mlatcl

analytics:
  google: 
    tracking_id: UA-184894912-1
future: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
