logo: /assets/images/DATA_Logo_Primary_Colour_Light.png
logo_dark: 
contact_details:
  email: data-trusts@cst.cam.ac.uk
  address: |-
    15 JJ Thomson Ave,  \
    Cambridge,  \
    CB3 0FD
socials:
- link: https://twitter.com/
  label: Twitter
  icon: fa fa-twitter
footer_images:
  - image: /assets/images/DATA_Logo_Primary_Colour_Light.png
    link: "#"
  - image: /assets/images/cambridge-university.png
    link: https://www.cam.ac.uk/
